### ISSUE TITLE
Some comments about the project...

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [chinmoyp/screenrecorder#1]
1. can you please provide a sample of how to take a screenshot?
2. i think you should put a button to open the output file, and that the file should be in the app's path, and not in the top one, so that when it gets removed , the file gets removed too.
3. The sample showed a warning that I should not tick "don't show again", yet even though I did, it worked just fine.

**Comment by chinmoyp** [comment]
1.For taking a screenshot(I assume you are referring to the video) just open the app and tap the button and then go to home or do anything with the app in the background.
2.Will add the button to open the output file.

**Comment by AndroidDeveloperLB** [comment]
1. no, I'm talking about a screenshot. An image should be the output. not a video. the sample already does handle a video recording of the screen. I just think that because both are related, it would be great to have both in the same sample.
2. Thank you.

**Comment by chinmoyp** [comment]
That's a default feature with all android phones  clicking on the volume down button and power button simultaneously takes a snaphot.

**Comment by AndroidDeveloperLB** [comment]
I don't understand. There is an API for taking a screenshot. It's not available only built in for users.
Here's a StackOverflow post about it:
http://stackoverflow.com/a/34549690/878126
