### ISSUE TITLE
nothing is capturing !! 

### ISSUE THREAD

**Issue by hrgdeveloper** [chinmoyp/screenrecorder#3]
it makes the capture.mp4 file but  it's size is 0 kb and nothing is captured

**Comment by chinmoyp** [comment]
which version of android are you using and are the permissions handled correctly

**Comment by jeffreyliu8** [comment]
I enabled all permissions, this is android google pixel. Android Oreo.

**Comment by rahatshahzeb** [comment]
I have fixed the bug and created a pull request. #5
