### ISSUE TITLE
This code is not working in Marshmallow .

### ISSUE THREAD

**Issue by Naveenkant93** [chinmoyp/screenrecorder#4]
Hi I am testing this code in Lolipop and it works fine over there. But on MarshMallow not able to set Surface and not able to get Surface using mMediaRecorder.getSurface();.. Mainly on Redmi 3s Device

**Comment by abalta** [comment]
You need to handle permission with manually.

**Comment by HBiSoft** [comment]
I don't think this is related to permissions. If you do some searching on the internet you will soon find that this is a bug on MarshMallow devices. For some reason `MediaRecorder.getSurface()` returns null.

@Naveenkant93 Did you resolve this issue?
